# Generated by Django 2.1.5 on 2019-01-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VotingsBase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('authorid', models.IntegerField()),
                ('question', models.CharField(max_length=144)),
                ('options', models.IntegerField()),
                ('option1', models.CharField(max_length=50)),
                ('option1counter', models.IntegerField()),
                ('option2', models.CharField(max_length=50)),
                ('option2counter', models.IntegerField()),
                ('option3', models.CharField(max_length=50)),
                ('option3counter', models.IntegerField()),
                ('option4', models.CharField(max_length=50)),
                ('option4counter', models.IntegerField()),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
    ]
