# Generated by Django 2.1.5 on 2019-02-11 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportsHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=1000)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VotingHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('golosid', models.IntegerField()),
                ('userid', models.IntegerField()),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VotingsBase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('authorid', models.IntegerField()),
                ('question', models.CharField(max_length=144)),
                ('options', models.IntegerField()),
                ('option1', models.CharField(max_length=50)),
                ('option1counter', models.IntegerField()),
                ('option2', models.CharField(max_length=50)),
                ('option2counter', models.IntegerField()),
                ('option3', models.CharField(max_length=50)),
                ('option3counter', models.IntegerField()),
                ('option4', models.CharField(max_length=50)),
                ('option4counter', models.IntegerField()),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
    ]
