# Generated by Django 2.0.6 on 2019-02-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingsbase',
            name='multi',
            field=models.IntegerField(default=0),
        ),
    ]
