# Generated by Django 2.1.4 on 2019-02-09 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votation', '0002_votinghistory'),
        ('votation', '0002_reportshistory_votinghistory'),
    ]

    operations = [
    ]
