# Generated by Django 2.1.5 on 2019-02-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votation', '0003_merge_20190209_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votinghistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
